[package]
name = "entity"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
sea-orm = { version = "0.10", features = [
    "sqlx-postgres",
    "runtime-actix-rustls",
    "macros",
] }
